### ISSUE TITLE
DT2W doesn't work

### ISSUE THREAD

**Issue by krischen62** [Official-Ayrton990/android_kernel_xiaomi_sm8150#1]
From the update of R4 begining, DT2W doesn't work.
Hope be fixed soon.

**Comment by Official-Ayrton990** [comment]
At the moment, this can be fixed partially only. What I mean is that can be fixed for all aosp roms except Paranoid Android. But thanks I know about this issue

**Comment by Official-Ayrton990** [comment]
r6 released with dt2w fixed for all roms except PA. Check release please.

I'll close the issue, if you find more bugs feel free to open an issue

**Comment by krischen62** [comment]
> r6 released with dt2w fixed for all roms except PA. Check release please.
> 
> I'll close the issue, if you find more bugs feel free to open an issue

Thanks! It works after flashing r6 in my mi9 pixelexperienceplus 10 !
