### ISSUE TITLE
Fingerprint is no logger work with version 26 on MIUI

### ISSUE THREAD

**Issue by jonaskahn** [Official-Ayrton990/android_kernel_xiaomi_sm8150#4]
**System Info**

- Device: Cepheus
- Rom: MIUI EU v20.9.3

**Issues**
After I installed the kernel, the fingerprint starts working abnormally. I tried to remove and add a new one but I can never do it,  the system can't recognize.

**Comment by Official-Ayrton990** [comment]
Hi, thanks for reporting the issue by this place. I'm aware of the problem, this is happening on the newer releases of MIUI. Since I don't have access to MiCode and most of my code is using hacks, I can't promise you a working release, however I'm trying to find the issue and to clean the code to make it similar to the one that is closed source by xiaomi. I will left the issue open until I find out the solution, if not solution then it will be closed by that.

Regards!

**Comment by Official-Ayrton990** [comment]
> **System Info**
> 
> * Device: Cepheus
> * Rom: MIUI EU v20.9.3
> 
> **Issues**
> After I installed the kernel, the fingerprint starts working abnormally. I tried to remove and add a new one but I can never do it, the system can't recognize.

Please kindly check releases: https://github.com/Official-Ayrton990/Quantic-Kernel-AOSP-Cepheus/tree/09.09.20 I launched today a update with FOD fixed, I suggest you to read the bugs.

I will close the issue, as its solved.

Regards, Carlos Ayrton Lopez Arroyo (Ayrton990).

**Comment by jonaskahn** [comment]
> > **System Info**
> > 
> > * Device: Cepheus
> > * Rom: MIUI EU v20.9.3
> > 
> > **Issues**
> > After I installed the kernel, the fingerprint starts working abnormally. I tried to remove and add a new one but I can never do it, the system can't recognize.
> 
> Please kindly check releases: https://github.com/Official-Ayrton990/Quantic-Kernel-AOSP-Cepheus/tree/09.09.20 I launched today a update with FOD fixed, I suggest you to read the bugs.
> 
> I will close the issue, as its solved.
> 
> Regards, Carlos Ayrton Lopez Arroyo (Ayrton990).

I see, thank you :+1:

**Comment by jonaskahn** [comment]
Tested, and **it still does not work** :(

**Comment by Official-Ayrton990** [comment]
20.9.3 has fod issue even on stock as some chinese users reported, in low brightness dont work.

**Comment by jonaskahn** [comment]
In stock ROM, It worked for me even the lowest brightness. So strange?
